// Doortronix parts catalog. Owners pack ships with a new Condor operator —
// these SKUs are extras / replacements only.
window.DTX_PARTS = [
  {
    id: 'ma-ext-kit',
    sku: 'MA-EXT-KIT',
    name: 'Push rod extension kit',
    category: 'Operator',
    sell: 25,
    img: 'images/operator/ma-ext-kit.jpg',
    note: 'For push-arm reveals over 8″. One kit per leaf. Order clear or dark bronze to match the operator.',
  },
  {
    id: 'ma-end-plates',
    sku: 'MA-END-PLATES',
    name: 'Header end dress plates (plastic)',
    category: 'Operator',
    sell: 36,
    img: 'images/operator/ma-end-plates.jpg',
    note: 'Two black ABS plates and eight screws. For tight mounts when L-brackets are not used. Fits Condor and Dor-O-Matic / LCN Astro, Senior, and Mid Swing.',
  },
  {
    id: 'ma-owners-pack',
    sku: 'MA-OWNERS PACK',
    name: 'Owners pack with decals',
    category: 'Decals',
    sell: 150,
    img: 'images/operator/ma-owners-pack-detail.jpg',
    note: 'Included with a new swing operator. Order here for replacements or extras.',
  },
  {
    id: 'ma-decal01',
    sku: 'MA-DECAL01',
    name: 'Caution, Automatic Door',
    category: 'Decals',
    sell: 6,
    img: 'images/operator/ma-decal01-detail.jpg',
    note: '6" diameter. Same text both sides. Glass applications.',
  },
  {
    id: 'ma-decal02',
    sku: 'MA-DECAL02',
    name: 'Do Not Enter / Automatic Door',
    category: 'Decals',
    sell: 6,
    img: 'images/operator/ma-decal02-detail.jpg',
    note: 'Different text each side. Adhesive on the arrow side.',
  },
  {
    id: 'ma-decal03',
    sku: 'MA-DECAL03',
    name: 'Automatic Door / Do Not Enter',
    category: 'Decals',
    sell: 6,
    img: 'images/operator/ma-decal03-detail.jpg',
    note: 'Different text each side. Adhesive on the Do Not Enter side.',
  },
  {
    id: 'ma-decal04',
    sku: 'MA-DECAL04',
    name: 'Activate Switch to Operate',
    category: 'Decals',
    sell: 3,
    img: 'images/operator/ma-decal04-detail.jpg',
    note: 'Same text both sides. Glass applications.',
  },
  {
    id: 'ma-decal05',
    sku: 'MA-DECAL05',
    name: 'Pull / Push to Operate',
    category: 'Decals',
    sell: 3,
    img: 'images/operator/ma-decal05-detail.jpg',
    note: 'Different text each side. Adhesive on the Push side.',
  },
  {
    id: 'ma-decal06',
    sku: 'MA-DECAL06',
    name: 'Push / Pull to Operate',
    category: 'Decals',
    sell: 3,
    img: 'images/operator/ma-decal06-detail.jpg',
    note: 'Different text each side. Adhesive on the Pull side.',
  },
  {
    id: 'plate-1191',
    sku: '1191',
    name: '4×4 push plate, logo + PUSH TO OPEN',
    category: 'Plates',
    sell: 55,
    img: 'images/operator/plate-1191.jpg',
  },
  {
    id: 'plate-1198',
    sku: '1198',
    name: '4×4 push plate, text only',
    category: 'Plates',
    sell: 55,
    img: 'images/operator/plate-1198.jpg',
  },
  {
    id: 'plate-1199',
    sku: '1199',
    name: '4×4 push plate, logo only',
    category: 'Plates',
    sell: 55,
    img: 'images/operator/plate-1199.jpg',
  },
  {
    id: 'plate-1192',
    sku: '1192',
    name: 'Jamb switch, logo + text',
    category: 'Plates',
    sell: 55,
    img: 'images/operator/plate-1192.jpg',
  },
  {
    id: 'plate-1200',
    sku: '1200',
    name: 'Jamb switch, text only',
    category: 'Plates',
    sell: 55,
    img: 'images/operator/plate-1200.jpg',
  },
  {
    id: 'bea-10td900pb',
    sku: '10TD900PB',
    name: 'BEA 900 MHz transmitter',
    category: 'Radio',
    list: 76.40,
    sell: 55,
    img: 'images/operator/bea-10td900pb.jpg',
    note: 'Hardwired push-plate transmitter. Flag connectors, AAA battery.',
  },
  {
    id: 'bea-10rd900',
    sku: '10RD900',
    name: 'BEA 900 MHz receiver',
    category: 'Radio',
    list: 79.78,
    sell: 55,
    img: 'images/operator/bea-10rd900.jpg',
    note: 'Digital 900 MHz receiver. Up to 75 transmitters.',
  },
  {
    id: 'bea-10td900hh1',
    sku: '10TD900HH1',
    name: 'BEA 900 MHz keychain remote — one-button transmitter',
    category: 'Radio',
    list: 80.90,
    sell: 55,
    img: 'images/operator/bea-10td900hh1.jpg',
    note: 'One-button handheld / keychain. Needs a 10RD900 receiver.',
  },
  {
    id: 'bea-10ms31u-b',
    sku: '10MS31U-B',
    name: 'BEA Wave to Open touchplate, hardwired',
    category: 'Activation',
    list: 314.61,
    sell: 150,
    img: 'images/operator/bea-10ms31u-b.jpg',
    note: 'Black kit — single-gang + double-gang faceplates. Microwave, 4–24" range, IP54. Hardwired (no transmitter).',
  },
];
